Repository cosmo-epfl/librascal, pull requests merged in 2019-12, with the labels that each got.

#239 Bugfix/tidy gen scripts
  .pycodestyle
  bindings/rascal/neighbourlist/structure_manager.py
  bindings/rascal/representations/base.py
  bindings/rascal/representations/coulomb_matrix.py
  bindings/rascal/representations/spherical_covariants.py
  bindings/rascal/representations/spherical_expansion.py
  bindings/rascal/representations/spherical_invariants.py
  cmake/autopep8.cmake
  examples/center_select_example.py
  examples/coulomb_example.ipynb
  reference_data/inputs/small_molecules-20.json
  reference_data/tests_only/dft-smiles_500.ubjson
  reference_data/tests_only/kernel_reference.ubjson
  sandbox/playground.cc
  scripts/README.md
  scripts/developer_utils.py
  scripts/generate_gauss_legendre_ref_data.py
  scripts/generate_hyp1f1_ref_data.py
  scripts/generate_kernel_ref_data.py
  scripts/generate_modified_bessel_first_kind_ref_data.py
  scripts/generate_sorted_coulomb_ref_data.py
  scripts/generate_spherical_covariant_ref_data.py
  scripts/generate_spherical_expansion_ref_data.py
  scripts/generate_spherical_harmonics_ref_data.py
  scripts/generate_spherical_invariant_ref_data.py
  tests/python/python_representation_calculator_test.py
  tests/python/python_structure_manager_test.py
  tests/python/python_test_sparsify_fps.py
  tests/python/test_utils.py
  tests/test_manager_collection.cc
  tests/test_manager_collection.hh
Labels: bug

#158 Simplified layer utilities in cluster ref key - We need to talk about `compute_cluster_layer`
  bindings/bind_py_structure_manager.cc
  src/rascal/structure_managers/adaptor_center_contribution.hh
  src/rascal/structure_managers/adaptor_filter.hh
  src/rascal/structure_managers/adaptor_full_neighbour_list.hh
  src/rascal/structure_managers/adaptor_half_neighbour_list.hh
  src/rascal/structure_managers/adaptor_increase_maxorder.hh
  src/rascal/structure_managers/adaptor_neighbour_list.hh
  src/rascal/structure_managers/adaptor_strict.hh
  src/rascal/structure_managers/cluster_ref_key.hh
  src/rascal/structure_managers/species_manager.hh
  src/rascal/structure_managers/structure_manager.hh
  tests/test_cluster_ref_key.cc
  tests/test_cluster_ref_key.hh
Labels: invalid, maintenance

#241 Feat/half nl soap
  sandbox/playground.cc
  src/rascal/math/utils.hh
  src/rascal/representations/calculator_spherical_expansion.hh
  src/rascal/representations/calculator_spherical_invariants.hh
  src/rascal/structure_managers/adaptor_half_neighbour_list.hh
  src/rascal/structure_managers/adaptor_neighbour_list.hh
  src/rascal/structure_managers/structure_manager.hh
  tests/test_calculator.cc
  tests/test_calculator.hh
Labels: enhancement

#130 Property request forwarding and default manager function
  bindings/bind_py_structure_manager.cc
  docs/source/dev_guide/developer.rst
  docs/source/dev_guide/forwarding_of_property_requests.rst
  examples/forwarding_of_property_requests.cc
  examples/spherical_expansion_example.cc
  examples/spherical_invariants_example.cc
  performance/profiles/profile_spherical_expansion.cc
  src/rascal/models/kernels.hh
  src/rascal/representations/calculator_sorted_coulomb.hh
  src/rascal/representations/calculator_spherical_covariants.hh
  src/rascal/representations/calculator_spherical_expansion.hh
  src/rascal/representations/calculator_spherical_invariants.hh
  src/rascal/structure_managers/adaptor_center_contribution.hh
  src/rascal/structure_managers/adaptor_filter.hh
  src/rascal/structure_managers/adaptor_full_neighbour_list.hh
  src/rascal/structure_managers/adaptor_half_neighbour_list.hh
  src/rascal/structure_managers/adaptor_increase_maxorder.hh
  src/rascal/structure_managers/adaptor_neighbour_list.hh
  src/rascal/structure_managers/adaptor_strict.hh
  src/rascal/structure_managers/structure_manager.hh
  src/rascal/structure_managers/structure_manager_centers.hh
  src/rascal/structure_managers/structure_manager_collection.hh
  src/rascal/structure_managers/structure_manager_lammps.hh
  tests/test_calculator.cc
  tests/test_calculator.hh
  tests/test_properties.cc
  tests/test_properties.hh
Labels: bug, enhancement

#250 Added CommentReflow option to clang-format
  .clang-format
  src/rascal/structure_managers/structure_manager.hh
Labels: maintenance
