Repository cosmo-epfl/librascal, pull requests merged in 2019-11, with the labels that each got.

#187 fix 184
  src/math/bessel.hh
  tests/test_math_modified_bessel_first_kind.cc
Labels: bug

#175 Fixes #174
  bindings/rascal/models/kernels.py
  docs/source/reference/python.rst
  src/models/kernels.hh
  tests/python/python_binding_tests.py
  tests/python/python_models_test.py
  tests/test_kernels.cc
Labels: bug

#196 Bugfix/nl failure message
  bindings/rascal/__init__.py
  bindings/rascal/neighbourlist/structure_manager.py
  src/atomic_structure.hh
  src/structure_managers/structure_manager_centers.cc
  tests/reference_data/small_molecule_no_cell.json
  tests/test_atomic_structure.cc
Labels: bug

#204 feat/feature matrix getter
  bindings/bind_py_structure_manager.cc
  bindings/rascal/neighbourlist/structure_manager.py
  bindings/rascal/representations/base.py
  bindings/rascal/representations/spherical_covariants.py
  bindings/rascal/representations/spherical_expansion.py
  bindings/rascal/representations/spherical_invariants.py
  examples/SOAP_CSD500.ipynb
  examples/SOAP_example.ipynb
  examples/center_select_example.py
  examples/coulomb_example.ipynb
  examples/linked_cells.ipynb
  examples/spherical_expansion_example.ipynb
  scripts/developer_utils.py
  scripts/generate_gauss_legendre_ref_data.py
  scripts/generate_kernel_ref_data.py
  scripts/generate_modified_bessel_first_kind_ref_data.py
  scripts/generate_sorted_coulomb_ref_data.py
  scripts/generate_spherical_covariant_ref_data.py
  scripts/generate_spherical_expansion_ref_data.py
  scripts/generate_spherical_invariant_ref_data.py
  src/rascal/structure_managers/property_block_sparse.hh
  src/rascal/structure_managers/property_typed.hh
  src/rascal/structure_managers/structure_manager_collection.hh
  tests/python/python_models_test.py
  tests/python/python_representation_calculator_test.py
  tests/python/python_structure_manager_test.py
  tests/python/test_utils.py
  tests/test_calculator.cc
Labels: enhancement

#113 Feat/interpolator
  .circleci/config.yml
  CMakeLists.txt
  bindings/rascal/representations/spherical_covariants.py
  bindings/rascal/representations/spherical_expansion.py
  bindings/rascal/representations/spherical_invariants.py
  cmake/benchmark.cmake
  docs/source/dev_guide/benchmark_tutorial.rst
  docs/source/dev_guide/developer.rst
  docs/source/tutorials/benchmark_tutorial.cc
  performance/benchmarks/CMakeLists.txt
  performance/benchmarks/benchmark_interpolator.cc
  performance/benchmarks/benchmark_interpolator.hh
  performance/benchmarks/benchmark_spherical_representations.py
  performance/benchmarks/benchmarks.hh
  performance/benchmarks/benchmarks.py
  performance/profiles/CMakeLists.txt
  performance/profiles/profile_matrix_cubic_spline.cc
  performance/profiles/profile_scalar_cubic_spline.cc
  performance/profiles/profile_spherical_expansion.cc
  performance/profiles/profile_spherical_invariants.cc
  performance/profiles/utils.hh
  src/rascal/math/hyp1f1.hh
  src/rascal/math/interpolator.hh
  src/rascal/math/spherical_harmonics.hh
  src/rascal/representations/calculator_spherical_expansion.hh
  src/rascal/utils.hh
  tests/test_calculator.cc
  tests/test_calculator.hh
  tests/test_math_hyp1f1.cc
  tests/test_math_interpolator.cc
  tests/test_math_interpolator.hh
  tests/test_rascal_utils.cc
Labels: optimization

#215 Adapts get_dense_feature_matrix to new feature matrix getter
  performance/profiles/profile_spherical_expansion.cc
Labels: bug

#214 fix the bug with simple_cubic_8
  bindings/bind_py_structure_manager.cc
  performance/benchmarks/benchmark_interpolator.hh
  performance/profiles/profile_matrix_cubic_spline.cc
  performance/profiles/profile_scalar_cubic_spline.cc
  performance/profiles/profile_spherical_expansion.cc
  src/rascal/representations/calculator_spherical_invariants.hh
  src/rascal/structure_managers/property_block_sparse.hh
  tests/test_calculator.cc
  tests/test_calculator.hh
  tests/test_math_interpolator.hh
  tests/test_rascal_utils.cc
Labels: bug

#224 fix bug in ModifiedSphericalBessel
  scripts/generate_modified_bessel_first_kind_ref_data.py
  src/rascal/math/bessel.hh
  tests/reference_data/modified_bessel_first_kind_reference.json
  tests/reference_data/modified_bessel_first_kind_reference.ubjson
  tests/test_math.hh
  tests/test_math_modified_bessel_first_kind.cc
Labels: bug

#225 Feat/dvr grad
  performance/benchmarks/benchmark_spherical_representations.py
  scripts/generate_hyp1f1_ref_data.py
  src/rascal/math/bessel.cc
  src/rascal/math/bessel.hh
  src/rascal/math/hyp1f1.cc
  src/rascal/math/hyp1f1.hh
  src/rascal/representations/calculator_spherical_expansion.hh
  tests/reference_data/hyp1f1_reference.ubjson
  tests/reference_data/mbfs_derivative_test.json
  tests/test_calculator.cc
  tests/test_calculator.hh
  tests/test_math.hh
  tests/test_math_hyp1f1.cc
  tests/test_math_modified_bessel_first_kind.cc
Labels: enhancement
